"""upgrade_table

Revision ID: 70e41a4ec99a
Revises: 548846f6b80f
Create Date: 2024-01-29 17:16:57.968952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e41a4ec99a'
down_revision: Union[str, None] = '548846f6b80f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('number_question', sa.Integer(), nullable=False))
    op.add_column('questions', sa.Column('right_answer', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'right_answer')
    op.drop_column('questions', 'number_question')
    # ### end Alembic commands ###
